config/routes.rb
Rails.application.routes.draw do
  root to: redirect("/login")

  devise_for :users do
    delete "/logout" => "devise/sessions#destroy", :as => :destroy_user_session
  end

  # Hijack devise authenticate_user! redirect to prevent 401.
  get "users/sign_in", to: "pages#login"

  # Unauthenticated pages
  get "login", to: "pages#login", as: "login"
  get "about", to: "pages#about", as: "about"
  get "contact", to: "pages#contact", as: "contact"
  get "signup", to: "pages#signup", as: "signup"

  # Authenticated pages
  get "home", to: "pages#home", as: "home"
  get "search", to: "pages#search", as: "search"

  resources :users
  resources :friends, only: %i[index destroy]
  resources :friend_requests, except: %i[edit new]
  resources :posts
  resources :comments, only: %i[create]
  resources :reactions, only: %i[create]
  resources :notifications, only: %i[destroy]
end

app/views/pages/_login.html.slim
= form_tag session_path(:user) do

  div.field
    label.label Email
    div.control
      = text_field_tag 'user[email]', "brxck@example.com", autofocus: true, class: 'input'
      
  div.field
    label.label Password
    div.control
      = password_field_tag 'user[password]', "testtest", class: 'input'

  div.field
    div.control
      = check_box_tag 'user[remember_me]'
      = label_tag 'user[remember_me]', ' Remember me'
      
  div.field.is-grouped
    div.control
      = submit_tag "Sign in", class: 'button is-success'
    div.control
      = link_to "Forgot password?", new_password_path(:user), class: 'button is-text'

app/views/pages/_signup.html.slim
= form_tag session_path(:user) do

  div.field
    label.label Email
    div.control
      = text_field_tag 'user[email]', nil, class: 'input'

  div.field
    label.label Password
    div.control
      = password_field_tag 'user[password]', nil, class: 'input'

  div.field
    label.label Confirmation
    div.control
      = password_field_tag 'user[password_confirmation]', nil, class: 'input'

  div.field
    div.control
      = check_box_tag 'user[remember_me]'
      = label_tag 'user[remember_me]', ' Remember me'

  div.field.is-grouped
    div.control
      = submit_tag "Sign in", class: 'button is-success'
    div.control
      = link_to "Forgot password?", new_password_path(:user), class: 'button is-text'

app/views/pages/about.html.slim
h1 Pages#about
p Find me in app/views/pages/about.html.slim

app/views/pages/contact.html.slim
h1 Pages#contact
p Find me in app/views/pages/contact.html.slim

app/views/pages/home.html.slim
.columns
  .column.is-one-quarter
    = render "shared/menu"

  .column.is-two-fifths
    article.card
      .card-content
        .media

          figure.media-left
            p.image.is-50x50
              = image_tag avatar(current_user, 50)

          .media-content
            = form_for current_user.posts.new do |f|
              .field
                = f.text_area :body,
                              class: "textarea", 
                              placeholder: "Write your next post!",
                              rows: "2",
                              id: "post-body-field"
                              
              .field.is-grouped
                .control.has-icons-left
                  = f.text_field :link,
                                 class: "input is-small",
                                 placeholder: "Share a link",
                                 id: "post-link-field"
                  span.icon.is-small.is-left
                    = mi.link.md_18.to_s                  

                .control
                  label.post-image-button class="button is-success is-small"
                    | add image
                    span style="display:none"
                      = f.file_field :image,
                                    accept: "image/png,image/gif,image/jpeg"

                .control
                  = f.submit "post",
                             class: "button is-info is-small",
                             id: "post-submit-button"

    
    br

    = paginate @posts if params[:page]
    br
    = render @posts
    = paginate @posts

  = render "shared/notifications_panel"

app/views/pages/login.html.slim
div.section
  div.container
    div.columns
      div.column
        p The social network for the divine.
        p Now accepting mortals!
        br 
        p (Just hit the login button!)
      div.column
        h2.title Log In
        = render "login"

app/views/pages/search.html.slim
.columns
  .column.is-one-quarter
    = render "shared/menu"

  .column.is-two-fifths
    = form_tag search_path, method: :get
      .field
        .control.has-icons-left
          = text_field_tag :search,
                           params[:search],
                           placeholder: "Enter your search!",
                           class: "input is-expanded"
          span.icon.is-left == mi.search.md_24

      .box
        - if @results
          = render @results
          br
          = paginate @results
        - elsif params[:search]
          p No results found.
        - else
          = render @users
          br
          = paginate @users

  = render "shared/notifications_panel"

app/views/pages/signup.html.slim
= content_for :title { "Home" }

div.section
  div.columns
    div.column
    div.column
      h2.title Sign Up
      = render "signup"
    div.column